# Generated by Django 2.2.7 on 2020-02-12 17:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('developer', models.CharField(max_length=254)),
                ('price', models.PositiveIntegerField()),
                ('content', models.URLField()),
                ('uploadDate', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sales', models.PositiveIntegerField(default=0)),
                ('globalScore', models.PositiveIntegerField(null=True)),
                ('localScore', models.PositiveIntegerField(null=True)),
                ('gameStates', models.TextField(max_length=1000, null=True)),
                ('reviews', models.TextField(null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('logo', models.ImageField(blank=True, default='images/site_logo.jpg', upload_to='./images/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='games.GameCategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
